version: "3.9"

services:
  machine:
    image: cartesi/dapp:${DAPP_NAME:?undefined DAPP_NAME}-devel-machine
    command: xxd -c 256 -p hash; sleep 3
    volumes:
      - machine:/opt/cartesi/share/dapp-bin

  deployer:
    image: cartesi/rollups-cli:0.8.2
    depends_on:
      machine:
        condition: service_started
    command:
      [
        "create",
        "--rpc",
        "${RPC_URL:?undefined RPC_URL}",
        "--mnemonic",
        "${MNEMONIC:?undefined MNEMONIC}",
        "--templateHashFile",
        "/opt/cartesi/share/dapp-bin/hash",
        "--outputFile",
        "/deployments/${NETWORK:?undefined NETWORK}/${DAPP_NAME:?undefined DAPP_NAME}.json",
        "--inputDuration",
        "300",
        "--challengePeriod",
        "300",
        "--validators",
        "0x74d093F6911AC080897C3145441103DaBb869307,0x18930e8a66a1DbE21D00581216789AAB7460Afd0"
      ]
    volumes:
      - machine:/opt/cartesi/share/dapp-bin:ro
      - ./deployments:/deployments

volumes:
  machine: {}
